SELECT HUB.CUSTOMER_PK AS DIM_CUSTOMER_KEY,
       HUB.CUSTOMERKEY        AS CUSTOMER_ID,
       SAT.*
FROM   {{ref('hub_customer')}} AS HUB
INNER JOIN {{ref('sat_customer')}} AS SAT
ON HUB.CUSTOMER_PK=SAT.CUSTOMER_PK
QUALIFY LEAD(SAT.LOAD_DATE) OVER (PARTITION BY HUB.CUSTOMER_PK ORDER BY SAT.LOAD_DATE) IS NULL