SELECT HUB.ORDER_PK AS DIM_ORDER_KEY,
       HUB.ORDERKEY     AS ORDER_ID,
       SAT.*
FROM   {{ref('hub_order')}} HUB
INNER JOIN {{ref('sat_order')}} SAT
ON  HUB.ORDER_PK = SAT.ORDER_PK 
QUALIFY LEAD(SAT.LOAD_DATE) OVER (PARTITION BY DIM_ORDER_KEY ORDER BY SAT.LOAD_DATE) IS NULL