SELECT 
    O_ORDERKEY AS ORDERKEY,
    O_CUSTKEY AS CUSTKEY,
    O_ORDERSTATUS AS ORDERSTATUS,
    O_TOTALPRICE AS TOTALPRICE,
    O_ORDERDATE AS ORDERDATE,
    O_ORDERPRIORITY AS ORDERPRIORITY,
    O_CLERK AS CLERK,
    O_SHIPPRIORITY AS SHIPPRIORITY,
    O_COMMENT AS COMMENT,
    CASE
         WHEN ORDERPRIORITY IN ( '2-HIGH', '1-URGENT' )
              AND TOTALPRICE >= 200000 THEN 'Tier-1'
         WHEN ORDERPRIORITY IN ( '3-MEDIUM', '2-HIGH', '1-URGENT' )
              AND TOTALPRICE BETWEEN 150000 AND 200000 THEN 'Tier-2'
         ELSE 'Tier-3'
       END  AS ORDERPRIORITYBUCKET
FROM {{source('tpch_sample','ORDERS')}} where o_custkey between '135011' and '135020'