SELECT 
    SRC.C_CUSTKEY AS CUSTOMERKEY,
    SRC.C_NAME AS CUSTOMER_NAME,
    SRC.C_ADDRESS AS CUSTOMER_ADDRESS,
    SRC.C_NATIONKEY AS CUSTOMER_NATION_KEY,
    SRC.C_PHONE AS CUSTOMER_PHONE,
    SRC.C_ACCTBAL AS CUSTOMER_ACCTBAL,
    SRC.C_MKTSEGMENT AS CUSTOMER_MKTSEGMENT,
    SRC.C_COMMENT AS CUSTOMER_COMMENT,
    RRN.N_REGIONKEY AS CUSTOMER_REGION_KEY,
    RRR.R_NAME AS CUSTOMER_REGION_NAME,
    RRN.N_NAME AS CUSTOMER_NATION_NAME,
    RRN.N_COMMENT AS CUSTOMER_NATION_COMMENT,
FROM {{source('tpch_sample','CUSTOMER')}} AS SRC
LEFT JOIN {{source('tpch_sample','NATION')}} AS RRN
    ON src.c_nationkey = rrn.n_nationkey
LEFT JOIN {{source('tpch_sample','REGION')}} AS RRR
    ON rrn.n_regionkey = rrr.r_regionkey
where c_custkey between '135011' and '135020'